tier_1_cities = [
    "Mumbai",
    "Delhi",
    "Bangalore",
    "Hyderabad",
    "Chennai",
    "Kolkata",
    "Pune",
    "Ahmedabad",
    "Jaipur",
    "Lucknow",
]

tier_2_cities = [
    "Nagpur",
    "Surat",
    "Kolkata",
    "Ahmedabad",
    "Bhopal",
    "Coimbatore",
    "Patna",
    "Vadodara",
    "Allahabad",
    "Visakhapatnam",
    "Vijayawada",
    "Madurai",
    "Rajkot",
    "Nashik",
    "Varanasi",
    "Srinagar",
    "Jodhpur",
    "Amritsar",
    "Ranchi",
    "Guwahati",
    "Dehradun",
]
